# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfog.proto\x12\x05\x66ogpb\"b\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.fogpb.SensorType\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x1f\n\x11StreamDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x12StreamDataResponse\x12\x1f\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x11.fogpb.SensorData\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"5\n\x12ProcessDataRequest\x12\x1f\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x11.fogpb.SensorData\";\n\x16UpdatePositionResponse\x12!\n\x08position\x18\x01 \x01(\x0b\x32\x0f.fogpb.Position*6\n\nSensorType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08VELOCITY\x10\x01\x12\r\n\tGYROSCOPE\x10\x02\x32T\n\rSensorService\x12\x43\n\nStreamData\x12\x18.fogpb.StreamDataRequest\x1a\x19.fogpb.StreamDataResponse0\x01\x32\r\n\x0b\x45\x64geService2a\n\x0c\x43loudService\x12Q\n\x11ProcessDataStream\x12\x19.fogpb.ProcessDataRequest\x1a\x1d.fogpb.UpdatePositionResponse(\x01\x30\x01\x42\nZ\x08./;fogpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./;fogpb'
  _globals['_SENSORTYPE']._serialized_start=369
  _globals['_SENSORTYPE']._serialized_end=423
  _globals['_SENSORDATA']._serialized_start=20
  _globals['_SENSORDATA']._serialized_end=118
  _globals['_STREAMDATAREQUEST']._serialized_start=120
  _globals['_STREAMDATAREQUEST']._serialized_end=151
  _globals['_STREAMDATARESPONSE']._serialized_start=153
  _globals['_STREAMDATARESPONSE']._serialized_end=206
  _globals['_POSITION']._serialized_start=208
  _globals['_POSITION']._serialized_end=251
  _globals['_PROCESSDATAREQUEST']._serialized_start=253
  _globals['_PROCESSDATAREQUEST']._serialized_end=306
  _globals['_UPDATEPOSITIONRESPONSE']._serialized_start=308
  _globals['_UPDATEPOSITIONRESPONSE']._serialized_end=367
  _globals['_SENSORSERVICE']._serialized_start=425
  _globals['_SENSORSERVICE']._serialized_end=509
  _globals['_EDGESERVICE']._serialized_start=511
  _globals['_EDGESERVICE']._serialized_end=524
  _globals['_CLOUDSERVICE']._serialized_start=526
  _globals['_CLOUDSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
