"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SensorData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    id: builtins.int
    type: builtins.str
    value: builtins.str
    timestamp: builtins.str
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        type: builtins.str = ...,
        value: builtins.str = ...,
        timestamp: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "timestamp", b"timestamp", "type", b"type", "value", b"value"]) -> None: ...

global___SensorData = SensorData

@typing.final
class StreamDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___StreamDataRequest = StreamDataRequest

@typing.final
class StreamDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___SensorData: ...
    def __init__(
        self,
        *,
        data: global___SensorData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___StreamDataResponse = StreamDataResponse

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Position = Position

@typing.final
class UpdatePositionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> global___Position: ...
    def __init__(
        self,
        *,
        position: global___Position | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["position", b"position"]) -> None: ...

global___UpdatePositionRequest = UpdatePositionRequest

@typing.final
class UpdatePositionResponse(google.protobuf.message.Message):
    """Empty response - no error means position was updated"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdatePositionResponse = UpdatePositionResponse

@typing.final
class ProcessDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___SensorData: ...
    def __init__(
        self,
        *,
        data: global___SensorData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___ProcessDataRequest = ProcessDataRequest

@typing.final
class ProcessDataResponse(google.protobuf.message.Message):
    """Empty response - data will be processed asynchronously
    and returned to the UpdatePosition endpoint
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ProcessDataResponse = ProcessDataResponse
